const productos = [
    {nombre:"Leche", precio:5600, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/Leche_entera_1L_5600.webp"},
    {nombre:"Crema de leche", precio:3600,categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/crema_leche.webp"},
    {nombre:"Queso en bloque", precio:11000, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/queso_bloque.webp"},
    {nombre:"Mantequilla", precio:10000, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/Mantequilla.webp"},
    {nombre:"Yogurt natural", precio:9700, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/Yogurt_natural.webp"},
    {nombre:"Yogurt con fruta", precio:4300, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/yogurt_confruta.webp"},
    {nombre:"Crema para batir", precio:6500, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/crema_batir.webp"},
    {nombre:"Yogurt de café", precio:4500, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/Yogurt_café.webp"},
    {nombre:"Queso Cottage", precio:8000, categoria:"lacteos", imagen:"../Recursos/Imagenes/lácteos/Queso_Cottage.webp"},
    {nombre:"Pan de queso", precio:2000, categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/pan_queso.webp"},
    {nombre:"Coissant de chocolate", precio:2500 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/croissant_chocolate.webp"},
    {nombre:"Rollo de canela", precio:3000 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/rollo_canela.webp"},
    {nombre:"Pan de bono", precio:3000 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/pan_De_bono.webp"},
    {nombre:"Almojabana", precio:2500 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/almojabana.webp"},
    {nombre:"Croissant", precio:2200 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/croissant.webp"},
    {nombre:"Pan tajado", precio:3000 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/pan_tajado.webp"},
    {nombre:"Pan francés", precio:500 , categoria:"panaderia", imagen:"../Recursos/Imagenes/panaderia/pan_frances.webp"},
    {nombre:"Ajo Und", precio:1000, categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/ajo.webp"},
    {nombre:"Brócoli", precio:5200, categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/brocoli.webp"},
    {nombre:"Mazorca Und",precio:2600 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/mazorca.webp"},
    {nombre:"Pepino Kg",precio:2900 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/pepino.webp"},
    {nombre:"Zanahoria Kg",precio:2400 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/zanahoria.webp"},
    {nombre:"Cebolla larga Atado",precio:7000 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/cebolla_larga.webp"},
    {nombre:"Cebolla cabezona Kg",precio: 4600 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/cebolla_cabezona.webp"},
    {nombre:"Papa Kg",precio:2800 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/papa.webp"},
    {nombre:"Tomate Kg",precio:3500 ,categoria:"frutas", imagen:"../Recursos/Imagenes/verduras/tomate.webp"},
    {nombre:"Detergente líquido", precio:25000, categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/detergente_liquido.webp"},
    {nombre:"Jabón en polvo", precio:18000 , categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/jabon_polvo.webp"},
    {nombre:"Desinfectante multiusos", precio:15000, categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/multiusos.webp"},
    {nombre:"Limpiavidrios", precio:5000 , categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/limpiavidrios.webp"},
    {nombre:"Ambientador en aerosol", precio:12000 , categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/ambientador.webp"},
    {nombre:"Jabón líquido para manos", precio:6800 , categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/jabon_manos.webp", descuento: 2},
    {nombre:"Crema dental", precio:7500, categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/crema_dental.webp"},
    {nombre:"Shampoo", precio:12000 , categoria:"aseo", imagen:"../Recursos/Imagenes/aseo/shampoo.webp"},
    {nombre:"Nevera", precio:1350000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/nevera.webp"},
    {nombre:"Freidora de aire", precio:170000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/freidora_aire.webp"},
    {nombre:"Batidora eléctrica", precio:110000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/batidora.webp"},
    {nombre:"Estufa", precio:97000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/estufa.webp"},
    {nombre:"Microondas", precio: 290000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/microondas.webp", descuento:25},
    {nombre:"Televisor", precio:845000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/televisor.webp"},
    {nombre:"Lavadora", precio:1100000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/lavadora.webp"},
    {nombre:"Aire acondicionado", precio:1480000, categoria:"electrodomesticos", imagen:"../Recursos/Imagenes/electrodomesticos/aire_acondicionado.webp", descuento: 10}
];